mutation CreateComment($commentInput: CommentInput!) {
    createComment(commentInput: $commentInput) {
        comment {
            title
            text
            owner {
                firstName
                lastName
            }
        }
        success
    }
}