#import "./fragments/overviewPost.gql"

query PostsByTagAndCategorySlug(
    $tagSlug: String
    $categorySlug: String
    $pageNr: Int
) {
    paginatedPosts(tagSlug: $tagSlug, categorySlug: $categorySlug, pageNr:$pageNr) {
        posts {
            ...OverviewPost
        }
        numPages
    }
}
