# Generated by Django 4.1 on 2022-08-22 13:50

import autoslug.fields
import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postlike_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, populate_from=blog.models.post_slug_populate_from, slugify=blog.models.slugify, unique=False),
        ),
        migrations.RunSQL(
            "UPDATE blog_post SET slug = replace(trim(lower(CONCAT(title,'-',id))), ' ', '-');", migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=blog.models.post_slug_populate_from, slugify=blog.models.slugify, unique=True),
        ),
    ]
