# Generated by Django 4.1 on 2022-08-24 11:49

import autoslug.fields
import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from=blog.models.category_slug_populate_from, slugify=blog.models.slugify, unique=False),
        ),
        migrations.RunSQL(
            "UPDATE blog_category SET slug = replace(trim(lower(CONCAT(name,'-',id))), ' ', '-');", migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=blog.models.category_slug_populate_from, slugify=blog.models.slugify, unique=True),
        ),
    ]
