# Generated by Django 4.1 on 2022-09-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
    ]
