# Generated by Django 4.1 on 2022-09-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_slug'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM blog_postlike WHERE id NOT IN (select MAX(id) from blog_postlike group by post_id, user_id);", migrations.RunSQL.noop),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
    ]
